name: CV to PDF

on: [push]

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://xgreenx.github.io/cv/
          outputFile: cv.pdf
      - name: Upload cv to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cv.pdf
          tag: latest
          overwrite: true
          body: "Latest CV in PDF"