name: CV to PDF

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Convert site into PDF
        run: |
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
          sudo apt install ./wkhtmltox_0.12.6-1.focal_amd64.deb
          wkhtmltopdf --user-style-sheet "file://${PWD}/pdf.css" https://xgreenx.github.io/cv/ cv.pdf

      - name: Upload cv to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cv.pdf
          asset_name: Anatolii_Osetymskyi_CV.pdf
          tag: latest
          overwrite: true
          body: "PDF version of the latest CV"