name: CV to PDF

on: [push]

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Convert site into PDF
        run: |
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
          sudo apt install ./wkhtmltox_0.12.6-1.focal_amd64.deb
          wkhtmltopdf https://xgreenx.github.io/cv/ cv.pdf
#      Looks ugly
#      - uses: misaelnieto/web_to_pdf_action@master
#        with:
#          webPageURL: https://xgreenx.github.io/cv/
#          outputFile: cv.pdf
      - name: Upload cv to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cv.pdf
          tag: latest
          overwrite: true
          body: "Latest CV in PDF"