name: CV to PDF

on: [push]

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://xgreenx.github.io/cv/
          outputFile: cv.pdf